### ISSUE TITLE
use chainhooks instead of `SmartContractMonitor` and `BlockchainImporter`

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/token-metadata-api#146]
This will also fix
* Dynamic mints for NFTs that exceed `max-supply`
* Dynamic supply tracking for FTs

**Comment by smcclellan** [comment]
This will help us with re-orgs (we get re-orgs free with chainhooks).

**Comment by rafaelcr** [comment]
Depends on https://github.com/hirosystems/chainhook/issues/234

**Comment by rafaelcr** [comment]
Blocked by https://github.com/hirosystems/chainhook/issues/376

**Comment by rafaelcr** [comment]
Blocked by https://github.com/hirosystems/chainhook/issues/387
