### ISSUE TITLE
metadata can't refresh when use IPFS link

### ISSUE THREAD

**Issue by LaserEyesNFT** [hirosystems/token-metadata-api#155]
These two contracts cannot refresh metadata, please help. Thanks.

https://explorer.hiro.so/txid/0xf62c2d1b9a19427370714e330705a71814fbffe4245ed699e424c9a448ae1109?chain=mainnet

https://explorer.hiro.so/txid/0x98d43f1f32525230d6b157a03ade30c17b214c3a28468385829f64449182eaaa?chain=mainnet

**Comment by rafaelcr** [comment]
Done, contracts refreshed
