### ISSUE TITLE
Filter FTs by address

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/token-metadata-api#170]
Hello team,
We'd like to build a new page in Explorer that lists all SIP-10 tokens and allow searching by token name and address.
reference: https://etherscan.io/tokens
To proceed with the new page, we need an endpoint that retrieves all tokens and also accepts a `query` parameter to enable searching. Please feel free to reach out if you have any questions.
Best,
Heidar
related to https://github.com/hirosystems/explorer/issues/1088

**Comment by smcclellan** [comment]
A draft of this is complete. @rafaelcr to follow up with @He1DAr on what exactly is needed here.

**Comment by rafaelcr** [comment]
@He1DAr does this endpoint cover your needs? https://github.com/hirosystems/token-metadata-api/pull/167
It's already merged but not yet released to prod

**Comment by rafaelcr** [comment]
Only missing filter is `address`, which should filter by deployer address
