### ISSUE TITLE
Add some restrictions to prevent phishing scams with tokens

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/token-metadata-api#173]
Is there any chance we can exclude this scam coin from the metadata server? I do not have a contract address yet, thinking you can find it without, and there could be more than one too. 

Should there be some restrictions to token names, for example to not allow urls? ...added to the standard to prevent things like this in the future?

![image](https://github.com/hirosystems/token-metadata-api/assets/33360391/589deda7-71f5-4c7b-8a9d-c850f0ad7ee6)

**Comment by Hero-Gamer** [comment]
I don't think I have the right answer but 
- If a token is 100% confirmed scam token. Would love if wallet can hide it on front end.. either wallet default the hide, or the user has a button to trigger the hide function.
- If a token is not 100% confirmed a scam, lays somewhere on the spectrum, then maybe don't hide on front end?
Would love to hear thoughts and discussion.

**Comment by smcclellan** [comment]
@314159265359879 Indeed this would be better suited as a client-side change. We (Hiro) don't want to be censoring transactions on our end. You're welcome to open a ticket in wallet if you're interested in the functionality there.
