### ISSUE TITLE
use CDN for token images

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/token-metadata-api#201]
Currently, token images are served from external servers. Some of them are extremely large which is causing performance issues.

![image](https://github.com/hirosystems/token-metadata-api/assets/97111756/89b34135-68e3-4cef-a5e5-df1dbe424d8e)
![image](https://github.com/hirosystems/token-metadata-api/assets/97111756/aa38bdd6-655c-4ed7-9f3d-8b18918bec4f)

To mitigate that, we need to serve images via CDN after sanitization and with optimized dimension.

**Comment by He1DAr** [comment]
Hey @rafaelcr, just checking in, any idea when this might be shipped? Thanks!

**Comment by rafaelcr** [comment]
@andresgalante @He1DAr update on this: API changes are code complete, I'm working with devops to get a staging instance deployed so I can start testing CDN uploads before releasing to prod
