### ISSUE TITLE
Wallets are not able to get the metadata of my token

### ISSUE THREAD

**Issue by Oyeins-GUI** [hirosystems/token-metadata-api#202]
**Describe the bug**
Leather and xverse are not getting the metadata of the token I deployed

Transaction ID - 0x9adf4c6d644f054f8d9c7af33566ac2fc0995dbf1392c2589672af519f4aa7d5
Address - SP16FECHZJPM4Z95D0Y2G7MSPGK0JHHCAE13X1PEW
Block#146882
Time stamp

**To Reproduce**
1. Go to https://explorer.hiro.so/token/SP16FECHZJPM4Z95D0Y2G7MSPGK0JHHCAE13X1PEW.runes-token?chain=mainnet

**Expected behavior**
Wallets and the explorer are suppose to get the metadata of the deployed token

**Screenshots**
![IMG_20240419_083016_401](https://github.com/hirosystems/token-metadata-api/assets/104744427/a6a3454b-360a-4b91-b20c-cc9e9682cda2)
![Screenshot_20240419-070152_Chrome](https://github.com/hirosystems/token-metadata-api/assets/104744427/a053bc79-3330-4887-9553-501eeb7d52b3)

**Desktop (please complete the following information):**
 - Browser - chrome, safari, firefox

**Smartphone (please complete the following information):**]
 - Browser - chrome, safari, firefox

**Additional context**

**Comment by 314159265359879** [comment]
@Oyeins-GUI Have you already tried sending a metadata notify transaction like this for your contract?
https://explorer.hiro.so/txid/0x4020031fc036a9aec7eb6e8ce6f0f0f38a91420e5f446fba86c2a264cbd25407?chain=mainnet 

You can make this call using the explorer sandbox for example
https://explorer.hiro.so/sandbox/contract-call/SP1H6HY2ZPSFPZF6HBNADAYKQ2FJN75GHVV95YZQ.token-metadata-update-notify?chain=mainnet

When that is picked up alright you should see it reflected with this api:
https://api.hiro.so/metadata/v1/ft/SP16FECHZJPM4Z95D0Y2G7MSPGK0JHHCAE13X1PEW.runes-token?chain=mainnet
Current response is `{"error":"Token metadata is unreachable or does not conform to SIP-016"}`
SIP16 can be found here: https://github.com/stacksgov/sips/blob/main/sips/sip-016/sip-016-token-metadata.md

**Comment by Oyeins-GUI** [comment]
Okay
I've ran the update and the metadata is now been fetched properly, but the image is not still displaying

**Comment by Oyeins-GUI** [comment]
This is the token uri https://ipfs.io/ipfs/bafybeie3xjjfntqoudkstkmz25eoo5g3o6atcsctadlpzkj4d2gssfbclm/runes%20metadata.json
I wonder why it's not been displayed

**Comment by smcclellan** [comment]
Closing as the hosting of the image isn't related to the API. Please reopen if you believe this is still an issue on the API.
