### ISSUE TITLE
Recent Stacks NFTs not displaying image

### ISSUE THREAD

**Issue by brandonmarshall-tm** [hirosystems/token-metadata-api#218]
Many recent Stacks NFTs (including higher-profile collections like Mojo) are not displaying in Hiro Explorer or Leather. All of these examples display on Gamma without issue.

**Examples of STX NFT Collectibles where no image is displayed:**

- SPQ5CEHETP8K4Q2FSNNK9ANMPAVBSA9NN86YSN59.stxstone
- SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys
- SP2XMGYYTA1KRBKBYJHTW8CFWB2QYZKZE4BMHG3PJ.honorary-mojo
- SP18J677R5GRD7EKK0S096WVQW19SDPWTC0TCBTGV.project-indigo-the-nakamoto-protocol
- SP37MPXHEESNHHHXF5PV3353W7F9NEZ4T13GZWJD4.batch-1715205186974

The URL Leather is trying to pull from which is resulting in an error:

- https://api.hiro.so/metadata/v1/nft/SPQ5CEHETP8K4Q2FSNNK9ANMPAVBSA9NN86YSN59.stxstone/1
- https://api.hiro.so/metadata/v1/nft/SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys/1
- https://api.hiro.so/metadata/v1/nft/SP2XMGYYTA1KRBKBYJHTW8CFWB2QYZKZE4BMHG3PJ.honorary-mojo/1
- https://api.hiro.so/metadata/v1/nft/SP18J677R5GRD7EKK0S096WVQW19SDPWTC0TCBTGV.project-indigo-the-nakamoto-protocol/4744
- https://api.hiro.so/metadata/v1/nft/SP37MPXHEESNHHHXF5PV3353W7F9NEZ4T13GZWJD4.batch-1715205186974/1

The same collections on Gamma:

- https://stacks.gamma.io/collections/SP37MPXHEESNHHHXF5PV3353W7F9NEZ4T13GZWJD4.batch-1715205186974
- https://stacks.gamma.io/collections/SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys
- https://stacks.gamma.io/collections/SP2XMGYYTA1KRBKBYJHTW8CFWB2QYZKZE4BMHG3PJ.honorary-mojo
- https://stacks.gamma.io/collections/SP18J677R5GRD7EKK0S096WVQW19SDPWTC0TCBTGV.project-indigo-the-nakamoto-protocol
- https://stacks.gamma.io/collections/SP37MPXHEESNHHHXF5PV3353W7F9NEZ4T13GZWJD4.batch-1715205186974

**Comment by rafaelcr** [comment]
hi @brandonmarshall-tm most of the NFTs are visible now, but I've noticed some of them don't have the proper SIP-016 formatting to show images, etc. so not all of the fields are visible.

**Comment by brandonmarshall-tm** [comment]
Thank you @rafaelcr! I can confirm most of the art I'd expect to see is showing up in my wallet now. Perhaps the only thing not displaying 100% is the animated `pizza-ninjas-on-sothebys`, but the static image is displaying, so definitely passable in the meantime.

It's interesting that the `batch-1715205186974` does not follow the SIP-016 standard since it was a POAP from an official Stacks Nakamoto event 😅 Will reach out to give the team a heads up for future ones.

**Comment by rafaelcr** [comment]
Sounds good, thanks! Closing this but please reopen if necessary

**Comment by DeeList** [comment]
There are some older NFTs and newer like the Stacks original Nakamojo NFT https://explorer.hiro.so/txid/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.mojo?chain=mainnet and Stacking DAO NFT https://explorer.hiro.so/txid/SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.stacking-dao-genesis-nft?chain=mainnet that do not display in Leather but show in Gamma.

<img width="258" alt="nfts" src="https://github.com/hirosystems/token-metadata-api/assets/132958967/795076f1-b7ec-4586-a867-461bc6b37738">

<img width="362" alt="nft2" src="https://github.com/hirosystems/token-metadata-api/assets/132958967/91017914-61c5-42e2-8e85-7aa4eaaaf810">
