### ISSUE TITLE
Explorer not loading the metadata associated with a token

### ISSUE THREAD

**Issue by FriendsFerdinand** [hirosystems/token-metadata-api#220]
**Describe the bug**
The metada associated with specific tokens isn't showing up on the explorer for this token: https://explorer.hiro.so/token/SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.zwstx-v1-2-1?chain=mainnet

**To Reproduce**
The metadata was updated with this transaction call: https://explorer.hiro.so/txid/0xbd155d2a4296800c736dfa9006ec8ce4591d477efeba198fae90bae40de4e7b6?chain=mainnet

This user holds some of the tokens as zststx: https://explorer.hiro.so/address/SP3X6G145Z6DV5H49MN0P0RK9SXY83ZN4ACM3RPMA?chain=mainnet

**Expected behavior**
The metadata should show the image in the explorer and in the wallet.

**Screenshots**
<img width="322" alt="image" src="https://github.com/hirosystems/token-metadata-api/assets/35247240/d91fa593-bf8b-451e-99bc-de2b75c6e9af">

The shown tokens should be displaying the image in the metadata.

**Additional context**
The metadata was showing correctly for an older version here: https://explorer.hiro.so/txid/0xfdb10cdd68f72265e8e6ca50e488f34022d1652df3da6d1886c9acdfad14de0c?chain=mainnet

This is the content in the metadata
```.json
{
  "name": "zstSTX",
  "symbol": "ztSTX",
  "description": "Yield-bearing asset for ststx supplied in Zest.",
  "image": "https://token-meta.s3.eu-central-1.amazonaws.com/icons/zststx.png"
}
```

**Comment by sabbyanandan** [comment]
@rafaelcr: Please refresh these Zest contracts.

**Comment by rafaelcr** [comment]
@FriendsFerdinand there's an error in the metadata JSON files for those tokens. They're using special characters for open and close double quotes instead of the standard `"` character, for example:
```
Error: Parse error on line 2:
{  "name": “Zest STX”,  "symbo
-----------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```
Can you update these files so we can refresh?

**Comment by FriendsFerdinand** [comment]
@rafaelcr Ok, I'll fix that one. But what about zstSTX for example. I've set it to this: https://explorer.hiro.so/txid/0xbd155d2a4296800c736dfa9006ec8ce4591d477efeba198fae90bae40de4e7b6?chain=mainnet

Metadata Link: https://token-meta.s3.eu-central-1.amazonaws.com/zstSTX.json

Metadata Contents:
```.json
{
  "name": "zstSTX",
  "symbol": "ztSTX",
  "description": "Yield-bearing asset for ststx supplied in Zest.",
  "image": "https://token-meta.s3.eu-central-1.amazonaws.com/icons/zststx.png"
}
```

**Comment by rafaelcr** [comment]
The other two tokens are now fixed

**Comment by FriendsFerdinand** [comment]
@rafaelcr Ok, I fixed the json file with special characters

**Comment by rafaelcr** [comment]
Done @FriendsFerdinand all tokens refreshed
