### ISSUE TITLE
Missing metadata of Zest Diko and updating Zest stSTX 

### ISSUE THREAD

**Issue by FriendsFerdinand** [hirosystems/token-metadata-api#221]
**Describe the bug**
The metada associated with these specific tokens isn't showing up on the explorer:
SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.zdiko-v1-2

The metadata of this token has also been updated:
SP2VCQJGH7PHP2DJK7Z0V48AGBHQAW3R3ZW1QF4N.zststx-v1-2

**To Reproduce**
This user holds zststx and zdiko, the explorer should show the latest metadata:
https://explorer.hiro.so/address/SP3X6G145Z6DV5H49MN0P0RK9SXY83ZN4ACM3RPMA?chain=mainnet

**Expected behavior**
The metadata should show the image in the explorer and in the wallet.

This is the content in the metadata for zdiko:
```.json
{
  "name": "Zest Arkadiko",
  "symbol": "zDiko",
  "description": "Yield-bearing asset for DIKO supplied in Zest.",
  "image": "https://token-meta.s3.eu-central-1.amazonaws.com/icons/zDIKO.png"
}
```

This is the metadata content for zststx:
```.json
{
  "name": "zstSTX",
  "symbol": "ztSTX",
  "description": "Yield-bearing asset for ststx supplied in Zest.",
  "image": "https://token-meta.s3.eu-central-1.amazonaws.com/icons/zststx.png"
}
```

**Comment by rafaelcr** [comment]
Metadata is now refreshed
