### ISSUE TITLE
Can't fetch token metadata after 6 hours from the deployment

### ISSUE THREAD

**Issue by khoa-nvk** [hirosystems/token-metadata-api#223]
**Describe the bug**
This token was deployed 6 hours ago but the API can't fetch it

API: [https://api.hiro.so/metadata/v1/ft/SP2ZPX49RP2Z377P1HEFEEEB3M60SCED9XRD2SBHA.suii](https://api.hiro.so/metadata/v1/ft/SP2ZPX49RP2Z377P1HEFEEEB3M60SCED9XRD2SBHA.suii)

Deployed Tx: [https://explorer.hiro.so/txid/0xee70ad2f00d357ab6018b6d8d2edb8119ee5a7b6b2b81d49421c55707f8c3f1a?chain=mainnet](https://explorer.hiro.so/txid/0xee70ad2f00d357ab6018b6d8d2edb8119ee5a7b6b2b81d49421c55707f8c3f1a?chain=mainnet)

**Screenshots**
![metadata hiro ](https://github.com/hirosystems/token-metadata-api/assets/13306003/adfefa04-0460-4278-aa10-8f5486924b3f)

**Comment by rafaelcr** [comment]
@khoa-nvk the token is visible now. As I mentioned, the API had to wait until IPFS lifted its rate limit to try and fetch the metadata again. https://api.hiro.so/metadata/v1/ft/SP2ZPX49RP2Z377P1HEFEEEB3M60SCED9XRD2SBHA.suii
