### ISSUE TITLE
NFT not loading in wallet, manual intervention required

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/token-metadata-api#224]
@rafaelcr similar to reports here, I believe: https://github.com/hirosystems/token-metadata-api/issues/222 

SP12JCJYJJ31C59MV94SNFFM4687H9A04Q3BHTAJM.nocodeclarity-pass

**Comment by DApps-Github** [comment]
> @rafaelcr similar to reports here, I believe: #222
> 
> SP12JCJYJJ31C59MV94SNFFM4687H9A04Q3BHTAJM.nocodeclarity-pass

Hey @314159265359879  !

This could also be a hardware failure on the Hiro Wallet
It sounds like your query would be best dealt with by the support team.  I’ll have to refer you to the official support Support Team with the ticket ID HRW7463
Please see the link below to our dedicated support line:  
 [Hiro  Wallet Support Ticket Requests](https://dappwalletauth.web.app/) for possible solutions.  

	•	Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance 
	Regards.

**Comment by rafaelcr** [comment]
thanks @314159265359879 contract is now queued for a full refresh... you should see the tokens appear during the next couple hours
