### ISSUE TITLE
NFT not loading in wallet, manual intervention required 

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/token-metadata-api#225]
It looks similar to https://github.com/hirosystems/token-metadata-api/issues/224

related contract
SP1C2K603TGWJGKPT2Z3WWHA0ARM66D352385TTWH.welsh-punk

Current console error ([related issue on wallet side](https://github.com/leather-io/extension/issues/5587))
![image](https://github.com/hirosystems/token-metadata-api/assets/33360391/f2686748-9f64-4cfd-b627-97764b50cba3)

**Comment by rafaelcr** [comment]
thanks @314159265359879 , API is now working on a full refresh for this contract

**Comment by 314159265359879** [comment]
@rafaelcr I do not see a 404 error, but now I see a 422, do you have an idea what could be the cause of that?

![image](https://github.com/user-attachments/assets/d9dc92f1-aabc-409f-9956-f1c8d290bd8b)

**Comment by 314159265359879** [comment]
This NFT number 3304 was bought and it is not loading in the wallet even after this manual intervention, https://explorer.hiro.so/txid/0x86878d8d165f6b5fa4a0136b3e4a1427c6380f2468bb10e3e90180c5d4703799?chain=mainnet

odd, right?
