### ISSUE TITLE
Can't fetch token metadata

### ISSUE THREAD

**Issue by khoa-nvk** [hirosystems/token-metadata-api#226]
We can't fetch the token metadata for these newly deployed tokens:

https://api.hiro.so/metadata/v1/ft/SP45RYP4W83SMSCG5C7MZCM1EFVRJY4K6D0E05Z6.biaoqing
https://api.hiro.so/metadata/v1/ft/SP2FB951H8AM8RHJYKCZ46GYCSQC6DTQJYFY0KQ27.skibidi-toilet

**Comment by rafaelcr** [comment]
These were automatically picked up by the API with some delay, but issue is resolved
