### ISSUE TITLE
Token Metadata API Not Updating 

### ISSUE THREAD

**Issue by goatstx** [hirosystems/token-metadata-api#228]
**Describe the bug**
The token metadata api does not update the metadata information when the token uri is updated.

Transaction ID: 0x56efc5d0f1bac9a3a8f1a0cab2a18ce58955f16f29aa4d4e1088d6e46d4fd0ac
Address: SP2F4QC563WN0A0949WPH5W1YXVC4M1R46QKE0G14.memegoatstx
Block- #155717

**Expected behavior**
Metadata link: https://api.hiro.so/metadata/v1/ft/SP2F4QC563WN0A0949WPH5W1YXVC4M1R46QKE0G14.memegoatstx
Should have updated to this https://gaia.hiro.so/hub/1KdNvLJVWXxnr8JKswBksFAv1y3hMwCYrr/memegoatstx.json.

**Comment by rafaelcr** [comment]
Done
