### ISSUE TITLE
Missing metadata of BTCz

### ISSUE THREAD

**Issue by FriendsFerdinand** [hirosystems/token-metadata-api#267]
**Describe the bug**
The metada associated with this specific token isn't showing up on the explorer:
SM26AQGZBMDPN2NTH0DJWFESFV0NJC744F1GQVZ6Y.token-btc

**To Reproduce**
This user holds BTCz, the explorer should show the latest metadata:
https://explorer.hiro.so/address/SP1BQZ7QBWMRCYYFB51F5SGH2NJJ33R3BJQA71AQ0?chain=mainnet

**Expected behavior**
The metadata should show the image in the explorer and in the wallet.

This is the content in the metadata for BTCz:
```.json
{
  "name": "BTCz",
  "symbol": "BTCz",
  "description": "Bitcoin liquid staking token on the Stacks blockchain.",
  "image": "https://token-meta.s3.eu-central-1.amazonaws.com/icons/BTCz.png"
}
```

**Comment by rafaelcr** [comment]
@FriendsFerdinand token has been refreshed. When the API tried to pull the metadata originally, the server failed to deliver the JSON metadata so that's why it didn't appear.
