### ISSUE TITLE
token-metadata-api-client.getFtMetadata missing asset_identifier field

### ISSUE THREAD

**Issue by pradel** [hirosystems/token-metadata-api#268]
**Describe the bug**

When calling `getFtMetadata`, the field `asset_identifier` is missing in the typescript types but is returned by the API.

**To Reproduce**
1. Call getFtMetadata
2. Try to access the asset_identifier field in typescript
3. See error

**Expected behavior**

The field should be accessible and be of type string

**Comment by rafaelcr** [comment]
@pradel please update to version 2.0.0 of the client to see the new properties. You'll need to adjust the way you use the lib a little bit but you'll get all the correct types now

**Comment by pradel** [comment]
@rafaelcr thanks, would it be possible to export the `paths` object to use the API types in the app?
